
package com.mycompany.tambo_mysql;
import Resources.ButtonAnimationUtils;
import javax.swing.JButton;

public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Regsitro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        derecha1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnIniciarSesion1 = new javax.swing.JButton();
        jbtnRegistrarme = new javax.swing.JButton();
        jtxtNombre = new javax.swing.JTextPane();
        jtxtApellido = new javax.swing.JTextPane();
        jtxtDireccion = new javax.swing.JTextPane();
        jtxtCelular = new javax.swing.JTextPane();
        jtxtEmail = new javax.swing.JTextPane();
        jtxtPass = new javax.swing.JTextPane();
        jtxtDNI = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE CLIENTE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(550, 600));

        derecha1.setBackground(new java.awt.Color(176, 18, 129));
        derecha1.setMinimumSize(new java.awt.Dimension(450, 750));
        derecha1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(104, 17, 130));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 17, 130));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Sprite-0002.png"))); // NOI18N
        derecha1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jbtnIniciarSesion1.setBackground(new java.awt.Color(230, 226, 32));
        jbtnIniciarSesion1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jbtnIniciarSesion1.setForeground(new java.awt.Color(176, 18, 129));
        jbtnIniciarSesion1.setText("VOLVER");
        jbtnIniciarSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnIniciarSesion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnIniciarSesion1MouseExited(evt);
            }
        });
        jbtnIniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarSesion1ActionPerformed(evt);
            }
        });
        derecha1.add(jbtnIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 240, 40));

        jbtnRegistrarme.setBackground(new java.awt.Color(230, 226, 32));
        jbtnRegistrarme.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jbtnRegistrarme.setForeground(new java.awt.Color(176, 18, 129));
        jbtnRegistrarme.setText("REGISTRARME");
        jbtnRegistrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnRegistrarmeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnRegistrarmeMouseExited(evt);
            }
        });
        jbtnRegistrarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarmeActionPerformed(evt);
            }
        });
        derecha1.add(jbtnRegistrarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 240, 40));

        jtxtNombre.setBackground(new java.awt.Color(176, 18, 129));
        jtxtNombre.setBorder(null);
        jtxtNombre.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(204, 204, 204));
        jtxtNombre.setText("Nombre");
        jtxtNombre.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

        jtxtApellido.setBackground(new java.awt.Color(176, 18, 129));
        jtxtApellido.setBorder(null);
        jtxtApellido.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtApellido.setForeground(new java.awt.Color(204, 204, 204));
        jtxtApellido.setText("Apellidos");
        jtxtApellido.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, 30));

        jtxtDireccion.setBackground(new java.awt.Color(176, 18, 129));
        jtxtDireccion.setBorder(null);
        jtxtDireccion.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        jtxtDireccion.setText("Dirección");
        jtxtDireccion.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, 30));

        jtxtCelular.setBackground(new java.awt.Color(176, 18, 129));
        jtxtCelular.setBorder(null);
        jtxtCelular.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtCelular.setForeground(new java.awt.Color(204, 204, 204));
        jtxtCelular.setText("Celular");
        jtxtCelular.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 30));

        jtxtEmail.setBackground(new java.awt.Color(176, 18, 129));
        jtxtEmail.setBorder(null);
        jtxtEmail.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(204, 204, 204));
        jtxtEmail.setText("Correo");
        jtxtEmail.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 200, 30));

        jtxtPass.setBackground(new java.awt.Color(176, 18, 129));
        jtxtPass.setBorder(null);
        jtxtPass.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtPass.setForeground(new java.awt.Color(204, 204, 204));
        jtxtPass.setText("Contraseña");
        jtxtPass.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 200, 30));

        jtxtDNI.setBackground(new java.awt.Color(176, 18, 129));
        jtxtDNI.setBorder(null);
        jtxtDNI.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jtxtDNI.setForeground(new java.awt.Color(204, 204, 204));
        jtxtDNI.setText("Dirección");
        jtxtDNI.setPreferredSize(new java.awt.Dimension(50, 50));
        derecha1.add(jtxtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 200, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 200, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 200, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        derecha1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(derecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(derecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciarSesion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIniciarSesion1MouseEntered
        jbtnIniciarSesion1.setBorderPainted(false);
        jbtnIniciarSesion1.setFocusPainted(false);
        ButtonAnimationUtils.animateButtonOnMouseEnter(jbtnIniciarSesion1);
    }//GEN-LAST:event_jbtnIniciarSesion1MouseEntered

    private void jbtnIniciarSesion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIniciarSesion1MouseExited
        ButtonAnimationUtils.resetButtonSizeOnMouseExit((JButton) evt.getSource());    // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIniciarSesion1MouseExited

    private void jbtnIniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarSesion1ActionPerformed

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);//Centra el formulario
        this.dispose();
    }//GEN-LAST:event_jbtnIniciarSesion1ActionPerformed

    private void jbtnRegistrarmeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarmeMouseEntered
        jbtnRegistrarme.setBorderPainted(false);
        jbtnRegistrarme.setFocusPainted(false);
        ButtonAnimationUtils.animateButtonOnMouseEnter(jbtnRegistrarme);
    }//GEN-LAST:event_jbtnRegistrarmeMouseEntered

    private void jbtnRegistrarmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarmeMouseExited
        ButtonAnimationUtils.resetButtonSizeOnMouseExit(jbtnIniciarSesion1);    // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistrarmeMouseExited

    private void jbtnRegistrarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarmeActionPerformed
        String DNI=this.jtxtDNI.getText();
        String Nombre=this.jtxtNombre.getText();
        String Apellido=this.jtxtApellido.getText();
        String Direccion=this.jtxtDireccion.getText();
        String Celular=this.jtxtCelular.getText();
        String Email=this.jtxtEmail.getText();
        String Pass=this.jtxtPass.getText();
        
        Cliente cl=new Cliente(DNI, Nombre, Apellido, Direccion, Celular, Email, Pass);
        
        cl.RegistroDB();
        
        this.dispose();
    }//GEN-LAST:event_jbtnRegistrarmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel derecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton jbtnIniciarSesion1;
    private javax.swing.JButton jbtnRegistrarme;
    private javax.swing.JTextPane jtxtApellido;
    private javax.swing.JTextPane jtxtCelular;
    private javax.swing.JTextPane jtxtDNI;
    private javax.swing.JTextPane jtxtDireccion;
    private javax.swing.JTextPane jtxtEmail;
    private javax.swing.JTextPane jtxtNombre;
    private javax.swing.JTextPane jtxtPass;
    // End of variables declaration//GEN-END:variables
}
